- hosts: AtlantaSpines
  gather_facts: no
  tasks:

    - name: generate device intended config and documention
      import_role:
         name: arista.avd.eos_cli_config_gen

    - name: deploy configuration to device
      import_role:
         name: arista.avd.eos_config_deploy_eapi
